name: vsce-publish-extension
on:
  push:
    tags:
      - 'vscode-bpmn-modeler-v*'
jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build extension
        run: |
          npm install
          npm install -g vsce
          vsce package --out vs-code-bpmn-modeler.vsix
      - name: Upload .vsix to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./vs-code-bpmn-modeler.vsix
          asset_name: vs-code-bpmn-modeler.vsix
          tag: ${{ github.ref }}
          overwrite: true
      - name: Publish extension
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}